jobs:
- job: Job_1
  displayName: 'Agent job '
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
    fetchDepth: 1
  - task: PowerShell@2
    displayName: PowerShell Script
    inputs:
      targetType: inline
- job: Job_2
  displayName: Agent job 1
  dependsOn: Job_1
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
    fetchDepth: 1
  - task: PowerShell@2
    displayName: PowerShell Script
    inputs:
      targetType: inline
- job: Job_3
  displayName: Agent job 2
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
    fetchDepth: 1
  - task: PowerShell@2
    displayName: PowerShell Script
    inputs:
      targetType: inline
...
