apiVersion: v1 
kind: Pod
metadata: 
  name: myapp-pod
  labels:
    app: myapp
spec: 
  containers: 
    - name: myapp
      image: sandhyaavhad12345/pythonimg:latest
      imagePullPolicy: Always
      ports:
        - conatinerPort: 80  