apiVersion: apps/v1 
kind: ReplicaSet
metadata: 
  name: myapp2 
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: myapp2 
  template: #pods specification
    metadata: 
      name: myapp2-pod
      labels:
        app: myapp2
    spec: 
      containers: 
        - name: myapp2
          image: sandhyaavhad12345/pythonimg:latest
          ports:
            - conatinerPort: 80   